name: Auto Deploy to Testing Server

on:
  push:
    branches: [main]

jobs:
  deploy-to-testing:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            cd /home/deng/test_cicd/avc-test-py-mcp
            git pull origin main
            echo "部署完成啦！"